def get_player_data():
    data = [
        ("Christian McCaffrey", "gemini"),
        ("Saquon Barkely", "aquarius"),
        ("Ezekiel Elliot", "cancer"),
        ("Michael Thomas", "pisces"),
        ("Alvin Kamara", "leo"),
        ("Dalvin Cook", "leo"),
        ("Derrick Henry", "capricorn"),
        ("Davante Adam", "capricorn"),
        ("Joe Mixon", "leo"),
        ("Tyreek Hill", "pisces"),
        ("Julio Jones", "aquarius"),
        ("DeAndre Hopkins", "gemini"),
        ("Chris Godwin", "aquarius"),
        ("Nick Chubb", "capricorn"),
        ("Travis Kelce", "libra"),
        ("Josh Jacobs", "aquarius"),
        ("Kenyan Drake", "aquarius"),
        ("Miles Sanders", "taurus"),
        ("Aaron Jones", "sagittarius"),
        ("Kenny Golladay", "scorpio"),
        ("George Kittle", "libra"),
        ("Mike Evans", "leo"),
        ("Allen Robinson", "libra"),
        ("Patrick Mahomes", "libra"),
        ("Lamar Jackson", "capricorn"),
        ("Amari Cooper", "gemini"),
        ("Odell Beckham Jr.", "scorpio"),
        ("Juju Smith-Schuster", "sagittarius"),
        ("Todd Gurley", "leo"),
        ("Clyde Edwards-Helaire", "aries"),
        ("D.J. Moore", "aries"),
        ("Adam Thielen", "leo"),
        ("Leornard Fournette", "capricorn"),
        ("Chris Carson", "virgo"),
        ("Cooper Kupp", "gemini"),
        ("Melvin Gordon", "aries"),
        ("A.J. Brown", "cancer"),
        ("Calvin Ridley", "sagittarius"),
        ("Robert Woods", "aries"),
        ("Mark Andrews", "virgo"),
        ("James Conner", "taurus"),
        ("LeVeon Bell", "aquarius"),
        ("Courtland Sutton", "libra"),

    ]

    return data
